### ISSUE TITLE
How does the get user by id work?

### ISSUE THREAD

**Issue by Shuyinsama** [konfer-be/ts-express-typeorm#8]
First of all.. thanks for this awesome project. I have been using it to get a handle on typescript en typeorm. I really don't have an issue with this project, it works perfectly fine. I just don't get how the 'get' method works for getting a user by it's id.

It does not seem to use the 'one' method from the 'UserRepository'.

Would it be possible to get an explanation?

**Comment by konfer-be** [comment]
Hi ! If you're talking about the /api/v1/users/:id route, it goes through *UserController:get*, which calls *UserRepository:one*. You can log or do a step-by-step in debug mode to follow the path of the process. If you're talking about other route, I don't see ...

**Comment by Shuyinsama** [comment]
@konfer-be Thanks! I pulled this project from release 1.2.4 and then I tried to integrate a part into a demo project of my own by setting it up. I guess I copied some stuff incorrectly and my `get` method was all wrong! 

Apologies! Awesome work!

**Comment by konfer-be** [comment]
@Shuyinsama Yeah, it's indeed possible that some details have changed since that version. I have reviewed services & middlewares. I advise you to pull version 1.3.3, it improves / fixes bugs and details, and is more stable / scalable. Have a nice day !
