### ISSUE TITLE
Generate initial db

### ISSUE THREAD

**Issue by capital-d** [konfer-be/ts-express-typeorm#9]
Hi,

how can i generate initial database with typeorm cli sync or migration?

migration gave me "No changes in database schema were found - cannot generate a migration."
and scheme:sync "Schema syncronization finished successfully."

May be i'm do something wrong.

understood that question is semi related to your project, but hope that you can push my searches in right direction.

Thank you.

**Comment by konfer-be** [comment]
Hi ! If you wish generate your initial schema, migrations are not really the way to do that. In this conversation, you have a native solution: https://github.com/typeorm/typeorm/issues/809. I'm not really with that, first because that's depending of your database engine, next because that's a little bit 'tordu', in french in the text. But why not.

Else, you can simply create the database before sync it with typeorm CLI, by example for a MySQL engine:

```bash
> mysql -u root -p 
  > CREATE DATABASE db_name CHARACTER SET 'utf8';
  > exit;
> typeorm schema:sync
```

**Comment by capital-d** [comment]
Yes, tried the simple way.

Created db (postgres in my case) and run > tcs then > typeorm schema:sync
get "Schema syncronization finished successfully." but db is in initial state.

May be i had problem with connect to my db, will check.

Also after run of > tsc files compiled to:
dist
|-api
|--src
|---api

Like unexpected src/api in path.
I'm on windows locally, if it matters.

**Comment by konfer-be** [comment]
If you have this message from typeorm, it seems that the connection was found and is ok.  Ensure that you're on the good schema. About your compilation path, I don't know. It's depending of your tsconfig.json.

**Comment by capital-d** [comment]
Didn't know witch of y movement was right, but after server start, db is in right schema.
Maybe web view of postgres didn't update in time.

**Comment by capital-d** [comment]
Hi @konfer-be Steve,

don't want to flood repository with my questions, so i decided to ask in this.

Encounter another issue with postgres, in registration new user.
column "apikey" is not set to be nullable, so postgres not alow to make query.

Had to add nullable: true to "@Column" statement.
Maybe it work fine with another db type, without this.
So its more not a question, but info.

Thank you.

**Comment by konfer-be** [comment]
HI @capital-d ! No worries ... In initial implementation API key is auto-generated. So she's not nullable and it's not a problem because she's always filled and ... required. In theory. If she's not, the issue comes rather from that. Unless you don't wish work with an API key...

**Comment by capital-d** [comment]
Do i understand correctly API key is auto-generated from oAuth registration?
But in email registration user not provide apiKey.

**Comment by konfer-be** [comment]
It is not needed, the key is generated before insert in the subscriber. But that said, she's should generated only in the subscriber. It will be improved in a further version.

**Comment by capital-d** [comment]
Hi, thank you, indeed key is generated before insert, had no clue why it fail first time.

Had next question, not understand from where is userId parameter appear in guard.middleware.ts
src/api/core/middlewares/guard.middleware.ts
line 56
req.params.userId
make api request to /api/v1/users/profile and fail check in this line because my req.param is {}.

Thank you.

**Comment by konfer-be** [comment]
Yes, most part of the time this parameter is undefined because it is only exposed by some requests. So the else if clause is not always relevant. This use case is managed in the next release, with a lot of improvements about registration, validation and testing.
